<?php
/**
 * @file
 * Block implmentation and hooks for the Hello World module.
 */

/**
 * Implements hook_install().
 */
function hello_world_install() {
    $query = db_insert('block_node_type')
    ->fields(array('type', 'module', 'delta'))
    ->values(array(
      'type' => 'hello_world_article',
      'module' => 'hello_world',
      'delta' => 'hello_world',
    ))
    ->execute();
}

/**
 * Implements hook_page_build().
 */
function hello_world_page_build(&$page) {
  // Check to see if the page is a node page.
  if (arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == FALSE) {
    $node = menu_get_object();

    // Check that it is a hello-world-article node.
    if ($node->type == 'hello_world_article') {
      $block = module_invoke('hello_world', 'block_view', 'section_terms_enabled');

      $blocks['section_terms_enabled'] = array(
        '#markup' => '<div class="enabled-sections-block block"><h2 class="enabled-sections-title">'. $block['subject'] . '</h2>' . $block['content'] . '</div>',
      );

      // Set the region and check that the region exists before adding the
      // block into that region.
      $region = 'sidebar_second';
      if (isset($page[$region])) {
        $page[$region] = array_merge($page[$region], $blocks);
      }
      else {
        $page[$region] = $blocks;
      }
    }
  }
}

/**
 *  Implements hook_node_view().
 */
function hello_world_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'hello_world_article') {
    //save the node's original body content
    $body = $node->content['body'][0]['#markup'];

    //text to show on node page
    $extra_text = '<p><em>Content starts here!</em><p>';

    //prepend that text to the body
    $node->content['body'][0]['#markup'] = $extra_text . $body;
  }
}

/**
 * Implements hook_block_info().
 */
function hello_world_block_info() {
  $blocks = array();
  $blocks['section_terms_enabled'] = array(
    'info' => t('Enabled Section Terms'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function hello_world_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'section_terms_enabled':
      $block['subject'] = 'Hello World!';
      $block['content'] = _hello_world_block_content();
      $block['cache'] = DRUPAL_NO_CACHE;
      break;
  }
  return $block;
}

/**
 * Callback for grabbing all the enabled Section terms
 */
function _hello_world_block_content() {
  $output = "";

  $section_vocab = taxonomy_vocabulary_machine_name_load('sections');
  $section_terms = taxonomy_get_tree($section_vocab->vid);

  $output .= '<ul class="enabled-sections-list">';
  foreach ($section_terms as $term) {
    //load the attributes for the taxonomy term
    $term_attributes = taxonomy_term_load($term->tid);
    //check to see if the taxonomy term has 'enabled' checked
    if ($term_attributes->field_enabled[LANGUAGE_NONE][0]['value']) {
      $term_nodes = taxonomy_select_nodes($term_attributes->tid);

      foreach ($term_nodes as $term_nid) {
        $node = node_load($term_nid);
        $output .= '<li>' . l($node->title, 'node/' . $node->nid) . '</li>';
      }
    }
  }

  $output .= '</ul>';

  return $output;
}
